### ISSUE TITLE
报警通知功能中，未能正常推送到企业微信

### ISSUE THREAD

**Issue by chenruiyingry** [longtai-cn/hippo4j#199]
目前在验证Hippo4J过程中，配置报警通知遇到一点小问题，请教一下：
我是使用docker搭建的hippo4j-server，dockerfile如下：
```
FROM openjdk:8u322-jdk

WORKDIR /app
ADD hippo4j-server /app/hippo4j-server
ENV TZ=Asia/Shanghai
EXPOSE 6691
CMD java -Djava.ext.dirs=/usr/local/openjdk-8/jre/lib/ext:/usr/local/openjdk-8/lib/ext -Xloggc:/app/hippo4j-server/logs/hippo4j_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Xms1024m -Xmx1024m -Xmn512m -Dhippo4j.standalone=true -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/hippo4j-server/logs/java_heapdump.hprof -Dhippo4j.home=/app/hippo4j-server -jar /app/hippo4j-server/target/hippo4j-server.jar  --spring.config.location=/app/hippo4j-server/conf/application.properties --logging.config=/app/hippo4j-server/conf/hippo4j-logback.xml --server.max-http-header-size=524288 --server.tomcat.basedir=/app/hippo4j-server/bin
```
启动后观察docker日志无异常，并在客户端使用`1.2.0-RC4`版本的SpringBoot pom接入了服务端，yml文件配置如下：
```
spring:
  application:
    name: lbx-ai-biz-staff
  dynamic:
    thread-pool:
      server-addr: http://10.8.46.203:6691
      username: admin
      password: 123456
      namespace: lbx-ai
      item-id: ${spring.application.name}
```
以上功能，都可通过server动态修改和配置线程池：
![image](https://user-images.githubusercontent.com/36652469/164959294-87223f1c-f7b5-4b9d-bec6-a3436a2a3c05.png)

但在预警推送功能中发现问题：
我通过`报警通知`新增了通知类型为`CONFIG`的配置（如下图）
![1f6edeb9a1b478b854a28b2fb51b04d](https://user-images.githubusercontent.com/36652469/164959128-182100eb-1032-4171-a3ae-86125b55dafa.png)
![image](https://user-images.githubusercontent.com/36652469/164959281-de8003e8-8f1d-4ce3-a1a0-874df0c57083.png)
配置完成后，在`线程池管理`功能修改对应线程池ID的配置后，未收到企业微信的通知推送，另外耶配置了一个`ALARM`类型的预警，也没收到推送，麻烦大佬帮忙看一下~万分感谢
