### ISSUE TITLE
使用zk作为配置中心启动时日志报错

### ISSUE THREAD

**Issue by zhuanghaozhe** [longtai-cn/hippo4j#223]
## Question Report

在开始报告问题之前，请确保认真查看了以下步骤：

- 搜索打开和关闭的 [GitHub 问题](https://github.com/longtai-cn/hippo4j/issues)
- 阅读 [常见问题文档](https://hippo4j.cn/pages/9cc27d/)

请在提交问题之前回答这些问题，谢谢。

### 你使用了哪个项目？Hippo-4J Server 还是 Hippo-4J Core?
Hippo-4J Core  （zookeeper3.5.7）
### 你使用了哪个版本？
1.2.1（最新）
### 预期行为
启动时日志打印正常，不出现ERROR
### 实际行为
程序启动时日志打印出来了ERROR
### 原因分析（如果可以）
https://issues.apache.org/jira/browse/CURATOR-526
使用的是zookeeper3.5.7版本，需要将curator升级到5.2.0
```java
<dependency>
    <groupId>org.apache.curator</groupId>
    <artifactId>curator-framework</artifactId>
    <version>5.2.0</version>
</dependency>
```
### 问题重现步骤
1. 在hippo4j-example/hippo4j-core-zookeeper-spring-boot-starter-example/src/main/resources/application.yml配置如下

```yml
server:
  port: 8888

spring:
  application:
    name: dynamic-threadpool-zookeeper-example

  dynamic:
    thread-pool:
      config-file-type: properties
      zookeeper:
        zk-connect-str: hadoop102:2181,hadoop103:2181,hadoop104:2181
        config-version: 1.0.0
        root-node: /configserver/userproject
        node: zookeeper-demo
```

2. 在zk的/configserver/userproject/zookeeper-demo下面按照zookeeper-demo.properties创建配置信息
3. 启动项目
4. 日志打印
2022-05-14 20:56:49.459  **INFO** 17656 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : New config event received: {version=0, server.4=hadoop104:2888:3888:participant, server.3=hadoop103:2888:3888:participant, server.2=hadoop102:2888:3888:participant}
2022-05-14 20:56:49.466  **ERROR**17656 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : Invalid config event received: {version=0, server.4=hadoop104:2888:3888:participant, server.3=hadoop103:2888:3888:participant, server.2=hadoop102:2888:3888:participant}
2022-05-14 20:56:49.466  **INFO** 17656 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : New config event received: {version=0, server.4=hadoop104:2888:3888:participant, server.3=hadoop103:2888:3888:participant, server.2=hadoop102:2888:3888:participant}
2022-05-14 20:56:49.467  **ERROR**  17656 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : Invalid config event received: {version=0, server.4=hadoop104:2888:3888:participant, server.3=hadoop103:2888:3888:participant, server.2=hadoop102:2888:3888:participant}

### 用于重现此问题的示例代码（例如 GitHub 链接）
无
